# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026  mpc2emu contributors
#
# Part of mpc2emu -- https://github.com/lentferj/mpc2emu
# Contributions: Jan Lentfer, with AI assistance (see README).
"""The four auxiliary files a type-0 AKAI volume carries, as the machine writes them.

A volume this project builds from scratch is a **type-1 save**: programs and
samples only. The instrument's own SAVE offers a type-0 that additionally writes
an effects file, a multi, a drum-input page and a take list, and every real
library volume carries all four. A user reloading one of our volumes finds those
gone.

That was blocked for months on "what do we put in them?", with the reasonable
objection that an aux file holding invented contents is worse than an absent one.
**The objection was right and the premise was wrong: the choice is not between
decoding the formats and inventing values -- it is to reproduce what the
instrument itself writes.**

MEASURED, 45 specimens (2026-08-18): the S3000XL's own saves `VOLUME 001`,
`XCROSS 1` and `XCROSS 2`, plus six factory CD-ROMs.

    .T   160 B   ONE distinct content across all 45          -> a format CONSTANT
    .X  7312 B   9 distinct; the machine's own default        -> right for a
                 appears in exactly the 3 machine-written        volume we create,
                 volumes and nowhere else                        which has no
                                                                 effects assigned

WHAT THIS IS NOT. It is not a decode. Nothing here claims to know what a single
field inside `.X` or `.T` means, and the constants must not be edited as though
it did. The claim is the weaker, sufficient one: these files do not need to be
understood in order to be written correctly, because the correct contents are
observable.

PROVENANCE, recorded because a default that silently belongs to one OS release
ages badly and cannot be diagnosed afterwards:

    machine     Akai S3000XL, Jan Lentfer's unit
    OS          2.00 (as reported by the instrument)
    extracted   2026-08-18, from volumes the instrument itself saved to HD5
    corroborated  `.T` matches all six factory discs examined byte for byte;
                  `.X` matches the other two machine-written volumes

If a future unit or OS writes something different, that is a finding, not a bug
to paper over -- add the variant beside these rather than replacing them.
"""
import base64

#: Take list. Invariant across every specimen examined, machine and factory.
TAKE_LIST_T = base64.b64decode(
    "AAABHhYBCgoKCgoKCgoKKwAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAKCgoKCgoKCgoKCgoAAAAAAAM8fwAyAAAKADIAAAAAAA==")

#: Effects file, the machine's power-on default. A converted volume assigns no
#: effects, so this is the value the instrument would itself have written.
EFFECTS_X = base64.b64decode(
    "AgAADxAQDw0eHQoQExYPAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgMDAwMDAwMDAwMDAwMD"
    "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD"
    "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD"
    "HA8gDxwMCg8bCgEKAAHQBwAAYwAAABkFGgIyKNsyLgAFAAUAAAAFAAIPGQAFQQAUHgEAAAUAAAVj"
    "APT/AAAAAAwAAAAAAAQAAAAAAABCAAAAAABCAAAAQmMAYxkyAAACHhMREh4KHBkZFwoBAAAAAAMA"
    "DwBLEkIeUDIZAAAAAAAcDyAPHAwKDxsKAgoAAdAHAABjAAAAFAgbADIwATI4AAUABQAAAAUAAg8Z"
    "AAVBABQeAQAABQAABWMA9P8AAAAADAAAAAAABAAAAAAAAEIAAAAAAEIAAABCYwBjGTIAAA0XDw4T"
    "HxcKHBkZFwoAAAAAAgAKABkAQCNjMjIAAAAAABwPIA8cDAoPGwoDCgAB0AcAAGMAAAAfCBzbMjIB"
    "Mj7bBQAFAAAABQACDxkABUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAAAAAEAAAAAAAAQgAAAAAAQgAA"
    "AEJjAGMZMgAAGRYZGBEKEgsWFgoBCgAAAAAAADIAIwA+M1oyMgAAAAAAHA8gDxwMCg8bCgQKAAHQ"
    "BwAAYwAAABgBGwQyMvwyIgAFAAUAAAAFAAIPGQAFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAQA"
    "AAAAAABCAAAAAABCAAAAQmMAYxkyAAAGHRIZHB4KHA8gCgEKAAAAAAMAIwAjAEEoWjIyAAAAAAAc"
    "DyAPHAwKDxsKBQoAAdAHAABjAAAAGwUeAzIy/DIuAAUABQAAAAUAAg8ZAAVBABQeAQAABQAABWMA"
    "9P8AAAAADAAAAAAABAAAAAAAAEIAAAAAAEIAAABCYwBjGTIAACEXDw4THxcKEgsWFgEAAAAAAAAo"
    "ABkAQB5VMjIAAAAAABwPIA8cDAoPGwoGCgAB0AcAAGMAAAAYBBzbMjgHMjEABQAFAAAABQACDxkA"
    "BUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAAAAAEAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAAKh0XCxYW"
    "ChILFhYKAQAAAAABAA8APAY/GUYyMgAAAAAAHA8gDxwMCg8bCgcKAAHQBwAAYwAAABgDHNsyKNsy"
    "MQAFAAUAAAAFAAIPGQAFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAQAAAAAAABCAAAAAABCAAAA"
    "QmMAYxkyAAAtFgscEQ8KHBkZFwoBAAAAAAMAFAAUAEAyUDIyAAAAAAAcDyAPHAwKDxsKCAoAAdAH"
    "AABjAAAAIwcc2zI0BDIiAAUABQAAAAUAAg8ZAAVBABQeAQAABQAABWMA9P8AAAAADAAAAAAABAAA"
    "AAAAAEIAAAAAAEIAAABCYwBjGTIAAAALFwwTDxgeChwZGRcAAAAAAwAPAEYAPhkyMjIAAAAAABwP"
    "IA8cDAoPGwoJCgAB0AcAAGMAAAAbAxzbMijbMi0ABQAFAAAABQACDxkABUEAFB4BAAAFAAAFYwD0"
    "/wAAAAAMAAAAAAAEAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAABQ0ZGRYKEgsWFgoKCgAAAAABACMA"
    "Rh1CKGMyMgAAAAAAHA8gDxwMCg8bCgEAAAHQBwAAYwAAABQIHNsyKAYyNgAFAAUAAAAFAAIPGQAF"
    "QQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAQAAAAAAABCAAAAAABCAAAAQmMAYxkyAAAEHR4fDhMZ"
    "CgsXDAoKAAAAAAIANwAGHDIZHjIyAAAAAAAcDyAPHAwKDxsKAQEAAdAHAABjAAAAGgkc2zI1ADIi"
    "AAUABQAAAAUAAg8ZAAVBABQeAQAABQAABWMA9P8AAAAADAAAAAAABAAAAAAAAEIAAAAAAEIAAABC"
    "YwBjGTIAABYdHhwTGBEdChILFhYAAAAAAAAjABkAOShGMjIAAAAAABwPIA8cDAoPGwoBAgAB0AcA"
    "AGMAAAAZBhzbMjj+MiIABQAFAAAABQACDxkABUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAAAAAEAAAA"
    "AAAAQgAAAAAAQgAAAEJjAGMZMgAAJh0eCxEPCgsXDAoKCgAAAAACAEEAMgBALVUyMgAAAAAAHA8g"
    "DxwMCg8bCgEDAAHQBwAAYwAAABkJG/gyMgUyIgAFAAUAAAAFAAIPGQAFQQAUHgEAAAUAAAVjAPT/"
    "AAAAAAwAAAAAAAQAAAAAAABCAAAAAABCAAAAQmMAYxkyAAAbIRITHg8KHBkZFwoKAAAAAAMADwAy"
    "FDU8PDIyAAAAAAAcDyAPHAwKDxsKAQQAAdAHAABjAAAAGgknADIyBzQiAAUABQAAAAUAAg8ZAAVB"
    "ABQeAQAABQAABWMA9P8AAAAADAAAAAAABAAAAAAAAEIAAAAAAEIAAABCYwBjGTIAAAoMHBMREh4K"
    "HBkZFwoAAAAAAwAoAAoiPSgyMjIAAAAAABwPIA8cDAoPGwoBBQAB0AcAAGMAAAAZCxwCGDgKMiwA"
    "BQAFAAAABQACDxkABUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAAAAAEAAAAAAAAQgAAAAAAQgAAAEJj"
    "AGMZMgAAKBAWHx4eDxwKEgsWFgAAAAAAADwAUA48MhkyMgAAAAAADRYPCxwKDRIZHB8dAAHQBwAA"
    "YwAAABQIHPsyOAUyPAgFAAUAAAAAAAMRLg4FQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAA"
    "AABCAAAAAABCAAAAQmMAYxkyAAABIQscDxIZHx0PCgoKAAAAAAIAFAAUADhQRjIyAAAAAAAcEw0S"
    "Cg0SGRwfHQoAAdAHAABjAAAAIgAc2zIo2zIiAAUABQAAAAAAAyAK8wVBABQeAQAABQAABWMA9P8A"
    "AAAADAAAAAAAAwAAAAAAAEIAAAAAAEIAAABCYwBjGTIAAAQOHB8XCgsXDBMPGB4AAAAABAAZAAAA"
    "PABFLTIAAAAAAB0WGSEKEBYLGBEPCgAB0AcAAGMAAAAiABzbMijbMiIABQAFAAAAAAACBGPcBUEA"
    "FB4BAAAFAAAFYwD0/wAAAAAMAAAAAAADAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAABhELHg8KHA8g"
    "DxwMAQAAAAAFAAoAAAA8Hlo8MgAAAAAAHhITDRUKEBYLGBEPAAHQBwAAYwAAACIAHNsyKNsyIgAF"
    "AAUAAAAAAAIIP9MFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQmMA"
    "YxkyAAAEFhMgDwoSGR8dDwoKAAAAAAMAGQBQHEEFXzIyAAAAAAAPGyYcDx0KEAskDxwAAdAHAABj"
    "AAAAIgAoBgMxBgYiAAUOBhAAAAAAAAYK0gVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAwAAAAAA"
    "AEIAAAAAAEIAAABCYwBjGTIAABcNFg8LHAocDyAPHAwAAAAAAQAjABkUQihjMjIAAAAAAB4SHBkL"
    "HiMKEAskDwAB0AcAAGMAAAAiABzbMijbMiIABQAFAAAAAAAADgTTBUEAFB4BAAAFAAAFYwD0/wAA"
    "AAAMAAAAAAADAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAAAxYZGBEKEgsWFgoCCgAAAAAAAA8AHgA6"
    "MlUyMgAAAAAADB8MDBYPIwoQCyQPAAHQBwAAYwAAACIAHNsyKNsyIgAFAAUAAAAAAAAwCeIFQQAU"
    "HgEAAAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQmMAYxkyAAADHA8gDxwdDwoc"
    "DyABAAAAAAYAFAAAADweVVAyAAAAAAAPDRIZChAWCxgRDxwAAdAHAABjAAAAIgAc2zIo2zIiAAUA"
    "BQAAAAAAAQRL0wVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAwAAAAAAAEIAAEsBHEJPAR1CYwBj"
    "GTIAAAgaDxwNHx0dCgsXDAoAAAAAAwAPABQfNh4yMjIAAAAAABwZHgscIwoNCwwKCgAA0AcAAGMA"
    "AAAiABzbMijbMiIABQAFAAAAAQACDxkABkUAFBkBAAAFAAAFYwD0/wAAAAAMAAAAAAADAAAAAAAA"
    "QgAAAAAAQgAAAEJjAGMZMgAABCETGA4jChwPIA8cDAAAAAACAFUAQQA8HloyMgAAAAAAHBkNFQoZ"
    "HBELGAoKAADQBwATSAAAACIAHNsyKNsyIgAFAAUAAAABAAIPGQAHRQAPIgEAAAUAAAVjAPT/AAAA"
    "AAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQmMAYxkyAAALHRcLFhYKEgsWFgoCAAAAAAEALQAKAD4e"
    "UDIyAAAAAAANFg8LGAoRHxMeCxwAAdAHAABjAAAAIgAc2zIo2zIiAAUABQAAAAAAAxUS8AVBABQe"
    "AQAABQAABWMA9P8AAAAADAAAAAAAAwAAAAAAAEIAAEcBF0JPARhCYwBjGTIAAAUdEhkcHgocDyAK"
    "AgoAAAAAAwAoACgSQApaMjIAAAAAABcTFg4KDRYTGgoKCgAB0AcAG0AAAAAiABzbMijbMiIABQAF"
    "AAAAAAADFRLwBUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAAAAADAAAAAAAAQgAAyAAfQsYAHkJjAGMZ"
    "MgAAACELHA8SGR8dDwoCCgAAAAABAAUACwAzPCMyMgAAAAAAGSAcDhwTIA8KER4cAADQBwAvHAAA"
    "ACIAHNsyKNsyIgAFAAUAAAAAAAIVFOwFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAAAABC"
    "AAD6AB9C9gAhQmMAYxkyAAABDRkYDQ8cHgoSCxYWAAAAAAAAGQAZAD4tWjIyAAAAAAAXDx4LFgoS"
    "DxwZCgoAANAHAGMUAAAAIgAc2zIo2zIiAAUABQAAAAAAAhUZ8AVBABQeAQAABQAABWMA9P8AAAAA"
    "DAAAAAAAAwAAAAAAAEIAAE8BGUJGARtCYwBjGTIAAAUaGSEPHAoRCx4PCgoAAAAABQAtAAAAPB5j"
    "YzIAAAAAABwSGQ4PHQoaCxgKCgAA0AcAAGMAAAAiABzbMijbMiIABQAFAAAAAgACDxkABUEAFB4B"
    "AAAeCAAeSgD0/wAAAAAMAAAAAAADAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAAAx4TFg8OChwZGRcK"
    "CgAAAAADAEEAGQw8MiMyMgAAAAAAHhwPFxkWGQoKCgoKAADQBwAAYwAAACIAHNsyKNsyIgAFAAUA"
    "AAACAAIPGQAFQQAUHgEAAAUAACoqA/T/AAAAAAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQmMAYxky"
    "AAADHh8YGA8WCgoKCgoKAAAAAAAAAAAUADdQYzIyAAAAAAAWGRgRChcZGBkODhYAAdAHAABjAAAA"
    "IgAc2zIo2zIiAAUABQAAAAUAAg8ZAAVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAQCeAgAAMkIA"
    "AAAAAEIAAABCYwBjGTIAAAUhGRkOCiETGA4KCgoAAAAAAAA8ABkUNShfMjIAAAAAABoTGBEKGhkY"
    "EQoKCgAB0AcAAGMAAAAiABzbMijbMiIABQAFAAAABQACDxkABUEAFB4BAAAFAAAFYwD0/wAAAAAM"
    "AAAAAAABAJ4CAAAyQjIAAAAAQgAAAEJjAGMZHgAAARwPIA8cHQ8KHA8gAgAAAAAGADIAYwA8HmNi"
    "MgAAAAAAHR4PHA8ZCg4PFgsjAADQBwAAYwAAACIAHNsyKNsyIgAFAAUAAAAFAAIPGQAFQQAUHgEA"
    "AAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAAAABCAABPAS9CRwEtQmMAYxkaAAABESMXGAsdEx8XCgoK"
    "AAAAAAEAGQBjADsyCjIyAAAAAAAiGSAPHAoODxYLIwoAAdAHAABjAAAAIgAc2zIo2zIiAAUABQAA"
    "AAUAAg8ZAAVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAgAAAPoAMkIAAAAAAEIAAABCYwBjGTIA"
    "AAEWCxwRDwocGRkXCgIAAAAAAgAyABQGPC1aMjIAAAAAAB4SEw0VDxgPHAoBCgAB0AcAAGMAAAAi"
    "ABzbMijbMiIABQAFAAAAAwACDxkABUEAFB4BAAAFAAAFYwAjAAAAAADd/wAAAAADAAAAAAAAQgAA"
    "AAAAQgAAAEJjAGMZMgAAABELHg8KHA8gDxwMAgAAAAAEADIAAAA8HjdfMgAAAAAAHhITDRUPGA8c"
    "CgIKAAHQBwAAYwAAACIAHNsyKNsyIgAFAAUAAAADAAIPGQAFQQAUHgEAAAUAAAVjACMAAAAAAN3/"
    "AAAAAAMAAAAAAABCAABMAABCVQAAQmMAYxkyAAAACxcMEw8YDQ8KCgoKAAAAAAMAGQBfCEAKYzIy"
    "AAAAAAANFg8LHAoODx4fGA8AAdAHAABjAAAAGQoi8DIfCDI5CgIoASgAAAMAAg8ZAAVBABQeAQAA"
    "BQAAAWMDGQAAAAAA5/8AAAAAAwAAAAAAAEIAAAAAAEIAAABCYwBjGTIAAAALExwKIBkTDQ8KCgoA"
    "AAAAAAAyAAASKC1jMjIAAAAAABwZHgseExkYChoLGAAA0AcAAGMAAAAiABzbMijbMiIABQAFAAAA"
    "AgACDxkABUEAFB4BAAACHgABYwH0/wAAAAAMAAAAAAADAAAAAAAAQgAAAAAAQgAAAEJjAGMZMgAA"
    "BAwLHQ8XDxgeCgoKCgAAAAADAA8ANwguHigyMgAAAAAAHR4PHA8ZCg0SGRwdAAHQBwAUPAAAABQM"
    "IvsyLv4yOgYFAAUAAAAAAAIFRt0FQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAIAAAD6AAVCDwAA"
    "AABCAAAAQmMAYxkyAAAEDwscFiMKHA8QCgEKAAAAAAQACgAAADweX0EyAAAAAAAQFgsYEQ8cCh0a"
    "ExgAANAHAA9jAAAAIgAc2zIo2zIiAAUABQAAAAEAAg8ZAAM3ABRLAQAABQAABWMA9P8AAAAADAAA"
    "AAAAAwAAAAAAAEIAAGQAFEJkABRCYwBjGTIAAAEdGgsNDwocDyAPHAwAAAAAAAAAAAAAPkZjMjIA"
    "AAAAAB0hExwWIwodIQ8PGgAA0AcAAGMAAAAiACgGAjMGAiIAAigBKGMAAgACDxkABUEAFB4BAAAF"
    "AAABYwD0/wAAAAAMAAAAAAADAAAAAAAAQgAAAAAAQgAAAEJjAGMZHgAAAhcPDhMfFwoSCxYWAgAA"
    "AAABAC0AGSg6MkYyMgAAAAAACx8eIQsSCgwfDAwWAAHQBwAAYwAAACIAHNsyKAkFIgAFADMJAAAA"
    "AAIPGQAFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQmMAYxkyAAAa"
    "DwscFiMKHA8QCgIKAAAAAAMAAAAkAEIJYzIyAAAAAAANGRcPCgsYDgoRGQoAAegDNxk8AAAAIgAc"
    "9jIvDEs7CQUUBWMFAAAAAgUoHgVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAwAAAAAAAEIAAAAA"
    "AEIAAABCYwBjCi0AABweExESHgocGRkXCgIAAAAAAwAAABkAKBRjMjIAAAAAABoSCx0PDgocIBwM"
    "CgAB0AcAAGMAAAAiABzbMijbMiIABQAFAAAAAAAADAXZBUEAFB4BAAAFAAAFYwD0/wAAAAAMAAAA"
    "AAADAAAAAAAAQgAAAAAAQgAAAEIyAGPOAAAAKAsXDBMPGA0PCgIKCgAAAAADACgAXyhABWMyMgAA"
    "AAAAEBYLGBEPDgocIBwMAAHQBwAAYwAAACIAHNsyKNsyIgAFAAUAAAAAAAAGMtsFQQAUHgEAAAUA"
    "AAVjAPT/AAAAAAwAAAAAAAMAAAAAAABCAAAAAABCAAAAQjIAY84AAAAoFgscEQ8KERkWDgoKAAAA"
    "AAIAPABjAD8yVTIyAAAAAAANEhkcHx0OChwgHAwAAdAHAABjAAAAIgAc2zIo2zIiAAUABQAAAAAA"
    "AhEI+QVBABQeAQAABQAABWMA9P8AAAAADAAAAAAAAwAAAAAAAEIAAAAAAEIAAABCMgBjzhkAACgO"
    "HB8XCgwZGR4SCgoAAAAAAwAtABQAKCNVMjIAAAAAAA4ZGhoWDxwKHCAcDAAB0AcAAGMAAAAiABzb"
    "MijbMiIABQAFAAAAAgACDxkABUEAFB4BAAAFSRMFYwH0/wAAAAAMAAAAAAAEAAAAAAAAQgAAAAAA"
    "QgAAAEIyAGPOGQAAKBILHA4KIQsWFh0KCgAAAAAAAFoAKAA/HjIyMgAAAAAAHA8gDxwMCg0SCxMY"
    "AAHQBwAAYwAAACIAHNsyKNsyIgAFAAUAAAAFAAIPGQAFQQAUHgEAAAUAAAVjAPT/AAAAAAwAAAAA"
    "AAQAAAAAAABCAAAAAABCAAAAQmMAYxkAAAQwDhMQEB8dDxwKCgoKAAAAAAQAAAAAADweYx4yAAAA"
    "AAAQIgoeDxcaFgseDwoAAdAHAABjAAAAIgAc2zIo2zIiAAUABQAAAAAAAg8ZAAVBABQeAQAABQAA"
    "BWMA9P8AAAAADAAAAAAAAwAAAAAAAEIAAAAAAEIAAABCYwBjGTIAAAAcDyAKHg8XGhYLHg8AAAAA"
    "AAAAAAAAPB5jMjIAAAAAAA==")

#: Drum-input page. The format IS decoded (16 records of 9 from 0x10, second
#: bank at 0x5b -- see the aux-format notes), so this could be generated; the
#: machine's own default is used instead so that a volume we write is
#: indistinguishable from one it wrote, and so the four files come from one
#: consistent source rather than three.
DRUM_INPUTS_D = base64.b64decode(
    "AQAADhwfFwoTGBofHh0KACQzGgMFCyQDCSYyGQIECgoAACkyGQIECgoAAC8yGQIECgoAADcyGQIE"
    "CgoAAGMyGQIECgoAADwyGQIECgoAADwyGQIECgoAAAEAADwyGQIECgoAADwyGQIECgoAADwyGQIE"
    "CgoAADwyGQIECgoAADwyGQIECgoAADwyGQIECgoAADwyGQIECgoAADwyGQIECgoA")

#: Multi. Also decoded (1024-byte header + 16 parts x 192), same reasoning.
MULTI_M3 = base64.b64decode(
    "AAAAFx8WHhMKEBMWDwoKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEM"
    "kB4PHR4KGhwZERwLFwAAHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAA"
    "AAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAkAH0vwsMDQ4PEBESExQVFgAPHwMhbABNPfNQFAAAAWMAADIAAB4A"
    "AAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAABTAAACABMIBgwGAwYGBgUICgoFAAAAAAAA"
    "AAAAAAUIDgAICAAAAAAAAAAABEfbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAC"
    "HwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAA+AAAC"
    "AAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAD//wH0vwoKCgoKCgoKCgoKCgADHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAA"
    "AAAAAAAAAAAACgoKAAAAAABYAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAA"
    "AAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAEHwEYfwD/YwBQFAAAAWMA"
    "ADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoF"
    "AAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoK"
    "CgoKCgAFHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAA"
    "AAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAGHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAA"
    "AAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAI"
    "CAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAHHwEYfwD/YwBQ"
    "FAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYG"
    "BgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoK"
    "CgoKCgoKCgoKCgAIHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAA"
    "CgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAJHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIA"
    "AAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAA"
    "AAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAKHwEY"
    "fwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAI"
    "BgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/"
    "/wH0vwoKCgoKCgoKCgoKCgALHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAA"
    "AAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAA"
    "ABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAMHwEYfwD/YwBQFAAAAWMAADIA"
    "AB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAA"
    "AAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoK"
    "CgANHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAy"
    "AAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAD//wH0vwoKCgoKCgoKCgoKCgAOHwEYfwD/YwBQFAAAAWMAADIAAB4AAAIAAAEBAAAAAAAA"
    "AAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUICgoFAAAAAAAAAAAAAAUIDgAICAAA"
    "AAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wH0vwoKCgoKCgoKCgoKCgAPHwEYfwD/YwBQFAAA"
    "AWMAADIAAB4AAAIAAAEBAAAAAAAAAAAAAAAAAAAAAAAACgoKAAAAAAAyAAACAAAIBgwGAwYGBgUI"
    "CgoFAAAAAAAAAAAAAAUIDgAICAAAAAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w==")

#: The four files a type-0 save adds, in the order the instrument writes them.
AUX_FILES = (('TL1.T', TAKE_LIST_T),
             ('EFFECTS FILE.X', EFFECTS_X),
             ('DRUM INPUTS.D', DRUM_INPUTS_D),
             ('MULTI FILE.M3', MULTI_M3))

assert len(TAKE_LIST_T) == 160, "take list must be 160 bytes"
assert len(EFFECTS_X) == 7312, "effects file must be 7312 bytes"
assert len(DRUM_INPUTS_D) == 162, "drum-input page must be 162 bytes"
assert len(MULTI_M3) == 4096, "multi must be 4096 bytes"
